// One-click reconciliation report: builds a clean printable HTML document from the live run data
// and opens the browser print dialog (print-to-PDF). No dependency, no backend template.
import * as api from "./api.js";

const inr = (n) =>
  new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 2 }).format(Number(n || 0));

export async function openReport(run, evalData) {
  if (!run) return;
  let exceptions = [];
  try {
    exceptions = (await api.getExceptions(run.runId)).items;
  } catch {
    exceptions = [];
  }
  const m = run.meta;
  const acc = evalData?.accuracy;
  const fees = m.fee_totals_paise || {};

  const metricRow = (label, value) =>
    `<tr><td>${label}</td><td style="text-align:right;font-variant-numeric:tabular-nums">${value}</td></tr>`;

  const exRows = exceptions
    .map(
      (e) =>
        `<tr><td>${e.id}</td><td>${e.date}</td><td style="text-align:right">${inr(e.amount)}</td>` +
        `<td>${e.category}</td><td>${e.severity}</td><td>${e.status}</td></tr>`
    )
    .join("");

  const html = `<!doctype html><html><head><meta charset="utf-8"><title>ReconMint Report ${run.runId}</title>
  <style>
    *{box-sizing:border-box} body{font-family:-apple-system,Segoe UI,Roboto,sans-serif;color:#1e293b;margin:40px;font-size:13px}
    h1{font-size:22px;margin:0 0 4px} .sub{color:#64748b;font-size:12px;margin-bottom:24px}
    h2{font-size:13px;text-transform:uppercase;letter-spacing:.05em;color:#64748b;margin:28px 0 10px;border-bottom:1px solid #e2e8f0;padding-bottom:6px}
    table{width:100%;border-collapse:collapse;margin-bottom:8px}
    td,th{padding:6px 8px;border-bottom:1px solid #f1f5f9;font-size:12px}
    th{text-align:left;color:#94a3b8;text-transform:uppercase;font-size:10px;letter-spacing:.05em}
    .grid{display:grid;grid-template-columns:1fr 1fr;gap:24px}
    .badge{display:inline-block;background:#0f172a;color:#fff;font-size:10px;padding:2px 8px;border-radius:4px;text-transform:uppercase;letter-spacing:.05em}
    .foot{margin-top:32px;color:#94a3b8;font-size:11px;border-top:1px solid #e2e8f0;padding-top:12px}
  </style></head><body>
    <h1>ReconMint — Reconciliation Report <span class="badge">Autonomous agent</span></h1>
    <div class="sub">Run ${run.runId}${run.isDemo ? " · demo (synthetic data)" : ""} · generated ${new Date().toLocaleString("en-IN")}</div>

    <div class="grid">
      <div>
        <h2>Run summary</h2>
        <table>
          ${metricRow("Records processed", m.settlement_active)}
          ${metricRow("Match rate", m.match_rate_pct + "%")}
          ${metricRow("Reconciled rate", m.reconciled_rate_pct + "%")}
          ${metricRow("Amount reconciled", inr((m.reconciled_amount_paise || 0) / 100))}
          ${metricRow("Processing time", m.elapsed_seconds + "s")}
          ${metricRow("Exceptions (needs review)", m.exceptions_total)}
        </table>
      </div>
      <div>
        <h2>Detection accuracy${acc ? "" : " (demo only)"}</h2>
        <table>
          ${acc ? metricRow("Precision", (acc.precision * 100).toFixed(0) + "%") : ""}
          ${acc ? metricRow("Recall", (acc.recall * 100).toFixed(0) + "%") : ""}
          ${acc ? metricRow("F1", acc.f1.toFixed(2)) : ""}
          ${acc ? metricRow("False positives / negatives", acc.false_positives + " / " + acc.false_negatives) : metricRow("Note", "accuracy requires ground truth (demo runs)")}
        </table>
        <h2>Fee composition</h2>
        <table>
          ${metricRow("MDR", inr((fees.mdr || 0) / 100))}
          ${metricRow("GST on MDR", inr((fees.gst || 0) / 100))}
          ${metricRow("TCS", inr((fees.tcs || 0) / 100))}
          ${metricRow("Refunds", inr((fees.refund || 0) / 100))}
        </table>
      </div>
    </div>

    <h2>Exceptions (${exceptions.length})</h2>
    <table>
      <thead><tr><th>Payment ID</th><th>Date</th><th style="text-align:right">Amount</th><th>Category</th><th>Severity</th><th>Status</th></tr></thead>
      <tbody>${exRows || '<tr><td colspan="6" style="color:#94a3b8">No exceptions.</td></tr>'}</tbody>
    </table>

    <div class="foot">Money math is deterministic and audited. AI is confined to explanation, verified against computed figures. Generated by ReconMint.</div>
    <script>window.onload = () => setTimeout(() => window.print(), 400);</script>
  </body></html>`;

  const w = window.open("", "_blank");
  if (!w) return;
  w.document.open();
  w.document.write(html);
  w.document.close();
}
